# Generated by Django 4.2.4 on 2023-09-11 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpotifyTokens',
            new_name='SpotifyToken',
        ),
    ]
